### PR TITLE
Remove tycho

### PR DESCRIPTION
**Pull request by cstamas**
Removes tycho completely, project is now two modules:
* sisu plain JAR
* tests (not deployed as before)

Builds upon https://github.com/eclipse/sisu.inject/pull/61

### CODE REVIEW

**Comment by cstamas** [comment]
@mcculls @kwin @laeubi ping

As I said, this PR "builds upon" https://github.com/eclipse/sisu.inject/pull/61 (adds +1 commit), so we can figure out what we want, but this change makes sisu "plain java" project now.

**Comment by cstamas** [comment]
I left sisu manifest, but am unsure is it needed (for consumers in eclipse)?

**Comment by kwin** [comment]
We should keep the OSGi bundle headers but let us use bnd-maven-plugin to generate them automatically from pom.xml and sources.

**Comment by cstamas** [comment]
@kwin I'd leave that to you, am not at home in osgi stuff...

**Comment by mcculls** [comment]
I can look over the OSGi part - previously we had 2 artifacts, one main jar and one extender whose manifest listed the activator that kick-started dynamic wiring of bundles. This was so people could choose to deploy it or not. We could always make that configurable via a system property if we want to flatten the project completely to a single module (although keeping at least one level in place does make it easier to add extra assemblies or BOM modules later on)

**Comment by cstamas** [comment]
So, IMHO let's move :smile: Lets merge this one and continue step-by-step?

**Comment by kwin** [comment]
@cstamas Based on your work I created #72 which removes the manual MANIFEST.MF

**Comment by cstamas** [comment]
Superseded by https://github.com/eclipse/sisu.inject/pull/72

**Pull request closed without merging**
