### PR TITLE
Fix Jacoco coverage repots in Sonar

### PR DESCRIPTION
**Pull request by cstamas**
Now that inject and plexus are consolidated, they should not step on each other toe, and write to top level target directory the report.

This does NOT fix Sonar, that for me, unknown reason, does not pick up generated Jacoco reports. Still, the reports on local builds are there and are usable.

### CODE REVIEW

**Comment by cstamas** [comment]
So, coverage is not picked up by Sonar... unsure why :thinking:

**Comment by cstamas** [comment]
Am giving up this fight with Sonar, anyone any clue?

**Comment by kwin** [comment]
Is this really that hard to achieve with Maven as outlined in https://github.com/jacoco/jacoco/wiki/MavenMultiModule? I think implementing a https://maven.apache.org/ref/3.9.7/maven-core/apidocs/org/apache/maven/execution/AbstractExecutionListener.html in Jacoco should allow to get rid of this additional module. WDYT @cstamas?

**Comment by cstamas** [comment]
No idea. Imho this is not jacoco (if you build locally all the files and reports are properly in place: per module reports but also the aggrgated one). It is more about sonat not picking up them, like it have clue where to look?

**Pull request merged**
