### PR TITLE
Disable annotation processor by default

### LINKED ISSUE #104: Don’t register annotation processor
Javac (even in v21) still executes all annotation processors found on the classpath by default. That is rarely necessary for https://github.com/eclipse/sisu.inject/blob/ba4cd7f6110d8705a82c4741c34768b4306950a9/org.eclipse.sisu.inject/META-INF/services/javax.annotation.processing.Processor#L1. Instead that annotation processor should always be explicitly registered if necessary (most of Sisu consumers leverage a dedicated maven goal for generating the index)

### PR DESCRIPTION
**Pull request by kwin**
This closes #104

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
Should be document how to enable without - `META-INF/services/javax.annotation.processing.Processor`

**Comment by mcculls** [comment]
> Should be document how to enable without - META-INF/services/javax.annotation.processing.Processor

Agree - another option would be to leave the services entry in place and use a system property to enable/disable (off by default)

**Comment by kwin** [comment]
> use a system property to enable/disable

As this is core functionality of Javac I wouldn't introduce another toggle: https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javac.html#BHCDIFEE -> option `-processor <classname>`. I will enrich the readme and site.

**Comment by kwin** [comment]
@mcculls Is https://github.com/eclipse/sisu.inject/blob/master/docs/index.html really manually crafted or created by some tool (if yes from what source)? WDYT about switching to a standardized Maven site here as well leveraging markdown?

**Review by slachiewicz — APPROVED** [review]

**Review by slawekjaranowski — APPROVED** [review]

**Pull request merged**
