### PR TITLE
Upgrade internal copy of ASM to 9.2

### LINKED ISSUE #29: Upgrade ASM in Sisu to 9.2 (Bugzilla Bug 546874)
This issue was created automatically with bugzilla2github
# Bugzilla Bug 546874
Date: 2019-04-30 13:35:25 -0400
From: Robert Scholte &lt;<eclipse@sourcegrounds.com>&gt;
To:   Stuart McCulloch &lt;<mcculls@gmail.com>&gt;
CC:   mcculls@gmail.com

Last updated: 2019-11-05 19:10:55 -0500

## Comment 3034851
Date: 2019-04-30 13:35:25 -0400
From: Robert Scholte &lt;<eclipse@sourcegrounds.com>&gt;

According to https://issues.apache.org/jira/browse/MNG-6580 Sisu is not capable in scanning Java class files with target/release 9+ due to an old version of ASM.
I've marked it as critical since there's no workaround (other than staying on a n older Java version).

## Comment 3093146
Date: 2019-11-05 19:10:55 -0500
From: Stuart McCulloch &lt;<mcculls@gmail.com>&gt;

I've put a small workaround in the 0.3.4 release which means the scanner now attempts to scan bytecode up to and including the Java 14 level. This was possible because the scanner only does a light scan of the class file and isn't affected by recent bytecode additions.

I'll leave this ticket open as I still want to get master onto the latest ASM release.

### PR DESCRIPTION
**Pull request by mcculls**
This fixes #29

### CODE REVIEW

**Comment by mcculls** [comment]
This was approved in CQ 23808

**Comment by bentmann** [comment]
Any chances of seeing this in a release?

**Comment by mcculls** [comment]
Hi @bentmann a new milestone release [0.9.0.M1](https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.inject/0.9.0.M1/) containing this change is now available on Maven central

**Comment by bentmann** [comment]
Yup, thanks, saw the milestone announcement a bit earlier.

**Pull request merged**
